---
abstract: 'delay string interpolation until you really want it'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: '0.007'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::6 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-Interpolate-Delayed
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  String::Interpolate::Delayed:
    file: lib/String/Interpolate/Delayed.pm
    version: '0.002'
requires:
  PadWalker: '1.0'
  PerlX::QuoteOperator: '0.04'
  String::Interpolate: '0.3'
  UNIVERSAL::ref: '0.09'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/String-Interpolate-Delayed/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=String-Interpolate-Delayed
  homepage: https://metacpan.org/release/String-Interpolate-Delayed
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-string-interpolate-delayed.git
version: '0.002'
