---
abstract: 'delay string interpolation until you really want it'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0.007
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: String::Interpolate::Delayed
name: String-Interpolate-Delayed
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  PadWalker: 1.0
  PerlX::QuoteOperator: 0.04
  String::Interpolate: 0.3
  UNIVERSAL::ref: 0.09
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=String-Interpolate-Delayed
  homepage: https://metacpan.org/release/String-Interpolate-Delayed
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-string-interpolate-delayed
version: 0.001
